### ISSUE TITLE
Is it possible to rely on a more recent version of mongodb?

### ISSUE THREAD

**Issue by wzrdtales** [punkave/appy#8]
Currently this project uses the 1.4.x version of mongodb, which does not build , native drivers are skipped, with the recent versions of node (4.0 and upwards), thus my question is, is there any functionality not available anymore in the newer drivers or could this dependency just be upgraded?

Thanks

**Comment by boutell** [comment]
Hmm, I just did it with no problems in node 4.1.1. I think you have an old
build lying around from before your node upgrade and need to type "npm
rebuild" or just nuke node_modules and npm install again.


On Mon, Oct 5, 2015 at 5:50 AM, Tobias Gurtzick <notifications@github.com>
wrote:

> Currently this project uses the 1.4.x version of mongodb, which does not
> build with the recent versions of node (4.0 and upwards), thus my question
> is, is there any functionality not available anymore in the newer drivers
> or could this dependency just be upgraded?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/appy/issues/8>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by wzrdtales** [comment]
You get it wrong... actually yes it works, but not with the native modules. If take a closer look you will notice that the builds are skipped and you result in this when starting:

    { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' } js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by wzrdtales** [comment]
@boutell Actually you will see this, you might think at the first moment the work has worked. Indeed it did not, the information that it failed is on the last line:

```
make: Entering directory '/home/tobi/_new/apostrophe-sandbox/node_modules/apostrophe-site/node_modules/appy/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
kerberos.target.mk:94: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
```

**Comment by wzrdtales** [comment]
@boutell Thus apostrophe and this module are **not** really compatible to node >= 4.0.0, they work but actually much slower than the other versions with working native extensions.

**Comment by boutell** [comment]
Yes, I see what you mean.

I will need to test with the latest in the 1.x series (which, hopefully,
does work with 4.x).

On Mon, Oct 5, 2015 at 8:20 AM, Tobias Gurtzick <notifications@github.com>
wrote:

> @boutell <https://github.com/boutell> Thus apostrophe and this module are
> *not* really compatible to node >= 4.0.0, they work but actually much
> slower than the other versions with working native extensions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/appy/issues/8#issuecomment-145510211>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
Have you come across any discussion of this issue elsewhere?

On Mon, Oct 5, 2015 at 9:32 AM, Tom Boutell <tom@punkave.com> wrote:

> Yes, I see what you mean.
>
> I will need to test with the latest in the 1.x series (which, hopefully,
> does work with 4.x).
>
> On Mon, Oct 5, 2015 at 8:20 AM, Tobias Gurtzick <notifications@github.com>
> wrote:
>
>> @boutell <https://github.com/boutell> Thus apostrophe and this module
>> are *not* really compatible to node >= 4.0.0, they work but actually
>> much slower than the other versions with working native extensions.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/appy/issues/8#issuecomment-145510211>.
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
Looks like there is no 1.4.x compatible with compiled BSON drivers in node
4.0.0, and 2.x is significantly different.

I need to look at whether the changes are enough to cause significant bc
problems in existing Apostrophe projects. Although they seem significant,
we've been using the mongodb 2.x driver for the forthcoming 0.6 release
(currently the unstable branch of the apostrophe module) and we really
haven't noticed any differences that impact our work.


On Mon, Oct 5, 2015 at 9:34 AM, Tom Boutell <tom@punkave.com> wrote:

> Have you come across any discussion of this issue elsewhere?
>
> On Mon, Oct 5, 2015 at 9:32 AM, Tom Boutell <tom@punkave.com> wrote:
>
>> Yes, I see what you mean.
>>
>> I will need to test with the latest in the 1.x series (which, hopefully,
>> does work with 4.x).
>>
>> On Mon, Oct 5, 2015 at 8:20 AM, Tobias Gurtzick <notifications@github.com
>> > wrote:
>>
>>> @boutell <https://github.com/boutell> Thus apostrophe and this module
>>> are *not* really compatible to node >= 4.0.0, they work but actually
>>> much slower than the other versions with working native extensions.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/punkave/appy/issues/8#issuecomment-145510211>.
>>>
>>
>>
>>
>> --
>>
>>
>> *THOMAS BOUTELL, *DEV & OPS
>> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
Hmm. While I can log into the 0.5 sandbox, I encountered a bug as soon as I
added media to the library. There is at least one difference that causes
erroneous behavior found within 5 minutes.

So I'm quite sure there would be gotchas for many people if I just slammed
the dependency in appy up to 2.x (:

We can't cause bc breaks in all 0.5 projects. So for now we have to
recommend the use of node 0.10.x to those who can't live with the
javascript BSON driver.

However I should note that we have a major client who insists on the
javascript BSON driver for other reasons, and their site still has a pretty
normal balance of CPU time between node and mongodb. Apostrophe does enough
data manipulation per request unrelated to BSON that a javascript BSON
driver is not really a major contributor to performance issues, in my
experience.

The forthcoming A2 0.6 has been using the 2.x mongodb driver from the
beginning and will be fully compatible with node 4.x. It is also a bc break
with 0.5, but there will be a clear roadmap for migration.


On Mon, Oct 5, 2015 at 9:40 AM, Tom Boutell <tom@punkave.com> wrote:

> Looks like there is no 1.4.x compatible with compiled BSON drivers in node
> 4.0.0, and 2.x is significantly different.
>
> I need to look at whether the changes are enough to cause significant bc
> problems in existing Apostrophe projects. Although they seem significant,
> we've been using the mongodb 2.x driver for the forthcoming 0.6 release
> (currently the unstable branch of the apostrophe module) and we really
> haven't noticed any differences that impact our work.
>
>
> On Mon, Oct 5, 2015 at 9:34 AM, Tom Boutell <tom@punkave.com> wrote:
>
>> Have you come across any discussion of this issue elsewhere?
>>
>> On Mon, Oct 5, 2015 at 9:32 AM, Tom Boutell <tom@punkave.com> wrote:
>>
>>> Yes, I see what you mean.
>>>
>>> I will need to test with the latest in the 1.x series (which, hopefully,
>>> does work with 4.x).
>>>
>>> On Mon, Oct 5, 2015 at 8:20 AM, Tobias Gurtzick <
>>> notifications@github.com> wrote:
>>>
>>>> @boutell <https://github.com/boutell> Thus apostrophe and this module
>>>> are *not* really compatible to node >= 4.0.0, they work but actually
>>>> much slower than the other versions with working native extensions.
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/punkave/appy/issues/8#issuecomment-145510211>.
>>>>
>>>
>>>
>>>
>>> --
>>>
>>>
>>> *THOMAS BOUTELL, *DEV & OPS
>>> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>>>
>>
>>
>>
>> --
>>
>>
>> *THOMAS BOUTELL, *DEV & OPS
>> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by wzrdtales** [comment]
@boutell No I havent came across another discussion of this issue.
Is there any eta of when the 0.6 release is incoming?

**Comment by boutell** [comment]
We'll start publishing 0.6 releases in a month or a little less, but keep
in mind it'll be a bc break; this is a long term support release, so we're
making changes now while we can (:

On Tue, Oct 6, 2015 at 2:54 AM, Tobias Gurtzick <notifications@github.com>
wrote:

> @boutell <https://github.com/boutell> No I havent came across another
> discussion of this issue.
> Is there any eta of when the 0.6 release is incoming?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/appy/issues/8#issuecomment-145759495>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
